package com.rms.entity.tdd;

// Generated 2015-7-15 14:05:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RmsDictDetail generated by hbm2java
 */
@Entity
@Table(name = "rms_dict_detail", catalog = "rms")
public class RmsDictDetail implements java.io.Serializable {

    private static final long serialVersionUID = 7734623500245890228L;
    private Integer detailId;

	private RmsDict	          rmsDict;
    private String detailName;
    private String detailValue;
    private String detailDesc;
    private Integer detailOrder;
    
    public RmsDictDetail() {
    }


    @Id
    @GeneratedValue
    @Column(name = "detail_id", unique = true, nullable = false)
    public Integer getDetailId() {
	return this.detailId;
    }

    public void setDetailId(Integer detailId) {
	this.detailId = detailId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dict_id")
	public RmsDict getRmsDict() {

		return this.rmsDict;
    }

    public void setRmsDict(RmsDict rmsDict) {
	this.rmsDict = rmsDict;
    }

    @Column(name = "detail_name", nullable = false, length = 200)
    public String getDetailName() {
	return this.detailName;
    }

    public void setDetailName(String detailName) {
	this.detailName = detailName;
    }

    @Column(name = "detail_value", nullable = false, length = 500)
    public String getDetailValue() {
	return this.detailValue;
    }

    public void setDetailValue(String detailValue) {
	this.detailValue = detailValue;
    }

    @Column(name = "detail_desc", length = 500)
    public String getDetailDesc() {
	return this.detailDesc;
    }

    public void setDetailDesc(String detailDesc) {
	this.detailDesc = detailDesc;
    }

    @Column(name = "detail_order")
    public Integer getDetailOrder() {
        return detailOrder;
    }

    public void setDetailOrder(Integer detailOrder) {
        this.detailOrder = detailOrder;
    }
}
