
package com.rms.entity.tdd;

// Generated 2015-7-16 23:13:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RmsFunctionInterfaceRalation generated by hbm2java
 */
@ Entity
@ Table (name = "rms_function_interface_relation", catalog = "rms")
public class RmsFunctionInterfaceRelation implements java.io.Serializable {

	private static final long	serialVersionUID	= 4058756684768335637L;
	private RmsFunctionInterfaceRelationId	id;

	public RmsFunctionInterfaceRelation () {

	}

	public RmsFunctionInterfaceRelation (RmsFunctionInterfaceRelationId id) {

		this.id = id;
	}

	@ EmbeddedId
	@ AttributeOverrides ({
			@ AttributeOverride (name = "funcId", column = @ Column (name = "func_id", nullable = false)),
			@ AttributeOverride (name = "IId", column = @ Column (name = "i_id", nullable = false)) })
	public RmsFunctionInterfaceRelationId getId () {

		return this.id;
	}

	public void setId (RmsFunctionInterfaceRelationId id) {

		this.id = id;
	}

}
