
package com.rms.entity.tdd;

// Generated 2015-7-16 23:13:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RmsFunctionInterfaceRalationId generated by hbm2java
 */
@ Embeddable
public class RmsFunctionInterfaceRelationId implements java.io.Serializable {

	private static final long	serialVersionUID	= 254624800384028648L;
	private int	funcId;
	private int	IId;

	public RmsFunctionInterfaceRelationId () {

	}

	public RmsFunctionInterfaceRelationId (int funcId, int IId) {

		this.funcId = funcId;
		this.IId = IId;
	}

	@ Column (name = "func_id", nullable = false)
	public int getFuncId () {

		return this.funcId;
	}

	public void setFuncId (int funcId) {

		this.funcId = funcId;
	}

	@ Column (name = "i_id", nullable = false)
	public int getIId () {

		return this.IId;
	}

	public void setIId (int IId) {

		this.IId = IId;
	}

	public boolean equals (Object other) {

		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RmsFunctionInterfaceRelationId))
			return false;
		RmsFunctionInterfaceRelationId castOther = (RmsFunctionInterfaceRelationId) other;

		return (this.getFuncId() == castOther.getFuncId()) && (this.getIId() == castOther.getIId());
	}

	public int hashCode () {

		int result = 17;

		result = 37 * result + this.getFuncId();
		result = 37 * result + this.getIId();
		return result;
	}

}
