package com.rms.entity.tdd;

// Generated 2015-7-16 23:13:41 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * RmsFunction generated by hbm2java
 */
@Entity
@Table (
    name = "rms_function",
    catalog = "rms")
public class RmsFunction implements java.io.Serializable {

	private static final long	serialVersionUID	= -6647952393466137805L;

	private Integer	          funcId;

	private String	          funcName;

	private String	          funcNameZh;

	private String	          funcDesc;

	private String	          funcUrl;

	private Integer	          funcParentId;

	private String	          funcType;

	private String	          isLastLevel;

	private Set<RmsInterface>	rmsInterfaceSet;

	@ManyToMany
	@JoinTable (
	    name = "rms_function_interface_relation",
	    joinColumns = {@JoinColumn (
	        name = "func_id")},
	    inverseJoinColumns = {@JoinColumn (
	        name = "i_id")})
	@LazyCollection (LazyCollectionOption.TRUE)
	public Set<RmsInterface> getRmsInterfaceSet () {

		return rmsInterfaceSet;
	}

	public void setRmsInterfaceSet (Set<RmsInterface> rmsInterfaceSet) {

		this.rmsInterfaceSet = rmsInterfaceSet;
	}

	public RmsFunction () {

	}

	public RmsFunction (String funcName, String funcNameZh, String funcDesc, String funcUrl, Integer funcParentId, String funcType,
	        String isLastLevel) {

		this.funcName = funcName;
		this.funcNameZh = funcNameZh;
		this.funcDesc = funcDesc;
		this.funcUrl = funcUrl;
		this.funcParentId = funcParentId;
		this.funcType = funcType;
		this.isLastLevel = isLastLevel;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "func_id",
	    unique = true,
	    nullable = false)
	public Integer getFuncId () {

		return this.funcId;
	}

	public void setFuncId (Integer funcId) {

		this.funcId = funcId;
	}

	@Column (
	    name = "func_name",
	    length = 100)
	public String getFuncName () {

		return this.funcName;
	}

	public void setFuncName (String funcName) {

		this.funcName = funcName;
	}

	@Column (
	    name = "func_name_zh",
	    length = 400)
	public String getFuncNameZh () {

		return this.funcNameZh;
	}

	public void setFuncNameZh (String funcNameZh) {

		this.funcNameZh = funcNameZh;
	}

	@Column (
	    name = "func_desc",
	    length = 5000)
	public String getFuncDesc () {

		return this.funcDesc;
	}

	public void setFuncDesc (String funcDesc) {

		this.funcDesc = funcDesc;
	}

	@Column (
	    name = "func_url",
	    length = 200)
	public String getFuncUrl () {

		return this.funcUrl;
	}

	public void setFuncUrl (String funcUrl) {

		this.funcUrl = funcUrl;
	}

	@Column (
	    name = "func_parent_id")
	public Integer getFuncParentId () {

		return this.funcParentId;
	}

	public void setFuncParentId (Integer funcParentId) {

		this.funcParentId = funcParentId;
	}

	@Column (
	    name = "func_type",
	    length = 10)
	public String getFuncType () {

		return this.funcType;
	}

	public void setFuncType (String funcType) {

		this.funcType = funcType;
	}

	@Column (
	    name = "is_last_level",
	    length = 2)
	public String getIsLastLevel () {

		return this.isLastLevel;
	}

	public void setIsLastLevel (String isLastLevel) {

		this.isLastLevel = isLastLevel;
	}

}
