package com.rms.entity.tdd;

// Generated 2015-6-25 11:50:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TddInterfaceCategoryRelationId generated by hbm2java
 */
@Embeddable
public class RmsInterfaceCategoryRelationId implements java.io.Serializable {

    private static final long serialVersionUID = -8931460261815498133L;
	private int IId;
	private int ICateId;

	public RmsInterfaceCategoryRelationId() {
	}

	public RmsInterfaceCategoryRelationId(int IId, int ICateId) {
		this.IId = IId;
		this.ICateId = ICateId;
	}

	@Column(name = "i_id", nullable = false)
	public int getIId() {
		return this.IId;
	}

	public void setIId(int IId) {
		this.IId = IId;
	}

	@Column(name = "i_cate_id", nullable = false)
	public int getICateId() {
		return this.ICateId;
	}

	public void setICateId(int ICateId) {
		this.ICateId = ICateId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RmsInterfaceCategoryRelationId))
			return false;
		RmsInterfaceCategoryRelationId castOther = (RmsInterfaceCategoryRelationId) other;

		return (this.getIId() == castOther.getIId())
				&& (this.getICateId() == castOther.getICateId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIId();
		result = 37 * result + this.getICateId();
		return result;
	}

}
