package com.rms.entity.tdd;

// Generated 2015-6-25 11:50:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TddInterfaceCategoryRelation generated by hbm2java
 */
@Entity
@Table(name = "rms_interface_category_relation", catalog = "rms")
public class RmsInterfaceCategoryRelation implements java.io.Serializable {

    private static final long serialVersionUID = 4991896675801808225L;
    private RmsInterfaceCategoryRelationId id;

    public RmsInterfaceCategoryRelation() {
    }

    public RmsInterfaceCategoryRelation(RmsInterfaceCategoryRelationId id) {
	this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name="IId", column = @Column(name = "i_id", nullable = false)),
    @AttributeOverride(name = "ICateId", column = @Column(name = "i_cate_id", nullable = false)) })
    public RmsInterfaceCategoryRelationId getId() {
	return this.id;
    }

    public void setId(RmsInterfaceCategoryRelationId id) {
	this.id = id;
    }

}
