package com.rms.entity.tdd;

// Generated 2015-6-25 11:50:53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * TddInterfaceCategory generated by hbm2java
 */
@Entity
@Table(name = "rms_interface_category", catalog = "rms")
public class RmsInterfaceCategory implements java.io.Serializable {

    private static final long serialVersionUID = 8342094242218451861L;
    private Integer ICateId;
    private String ICateName;

    private Set<RmsInterface> rmsInterfaceSet;
    
	@ManyToMany
	@JoinTable (
	    name = "rms_interface_category_relation",
	    joinColumns = {@JoinColumn (
	        name = "i_cate_id")},
	    inverseJoinColumns = {@JoinColumn (
	        name = "i_id")})
	@LazyCollection (LazyCollectionOption.TRUE)
	@JsonBackReference
	public Set<RmsInterface> getRmsInterfaceSet () {

		return rmsInterfaceSet;
	}

	public void setRmsInterfaceSet (Set<RmsInterface> rmsInterfaceSet) {

		this.rmsInterfaceSet = rmsInterfaceSet;
	}

	public RmsInterfaceCategory () {

	}

    public RmsInterfaceCategory(String ICateName) {
	this.ICateName = ICateName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "i_cate_id", unique = true, nullable = false)
    public Integer getICateId() {
	return this.ICateId;
    }

    public void setICateId(Integer ICateId) {
	this.ICateId = ICateId;
    }

    @Column(name = "i_cate_name", length = 500)
    public String getICateName() {
	return this.ICateName;
    }

    public void setICateName(String ICateName) {
	this.ICateName = ICateName;
    }

}
