package com.rms.entity.tdd;

// Generated 2015-6-25 11:50:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TddInterfacePramRelationId generated by hbm2java
 */
@Embeddable
public class RmsInterfaceParamRelationId implements java.io.Serializable {
    private static final long serialVersionUID = -3625372652287435160L;
    private int IId;
    private int ipId;

    public RmsInterfaceParamRelationId() {
    }

    public RmsInterfaceParamRelationId(int IId, int ipId) {
	this.IId = IId;
	this.ipId = ipId;
    }

    @Column(name = "i_id", nullable = false)
    public int getIId() {
	return this.IId;
    }

    public void setIId(int IId) {
	this.IId = IId;
    }

    @Column(name = "ip_id", nullable = false)
    public int getIpId() {
	return this.ipId;
    }

    public void setIpId(int ipId) {
	this.ipId = ipId;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof RmsInterfaceParamRelationId))
	    return false;
	RmsInterfaceParamRelationId castOther = (RmsInterfaceParamRelationId) other;

	return (this.getIId() == castOther.getIId()) && (this.getIpId() == castOther.getIpId());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getIId();
	result = 37 * result + this.getIpId();
	return result;
    }

}
