package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TddMemberExtend generated by hbm2java
 */
@Entity
@Table (
    name = "tdd_member_extend",
    catalog = "rms")
public class TddMemberExtend implements java.io.Serializable {

	private int	    userId;

	private String	realName;

	private Byte	gender;

	private String	birthday;

	private Integer	age;

	private String	phoneTel;

	private Integer	updateTime;

	private String	portraitBig;

	private String	portraitMiddle;

	private String	portraitSmall;

	private Integer	placeOrigin1;

	private Integer	placeOrigin2;

	private String	profession;

	private Integer	post;

	private String	autograph;

	private Integer	affective;

	public TddMemberExtend() {

	}

	public TddMemberExtend(int userId) {

		this.userId = userId;
	}

	public TddMemberExtend(int userId, String realName, Byte gender, String birthday, Integer age, String phoneTel, Integer updateTime,
	        String portraitBig, String portraitMiddle, String portraitSmall, Integer placeOrigin1, Integer placeOrigin2, String profession,
	        Integer post, String autograph, Integer affective) {

		this.userId = userId;
		this.realName = realName;
		this.gender = gender;
		this.birthday = birthday;
		this.age = age;
		this.phoneTel = phoneTel;
		this.updateTime = updateTime;
		this.portraitBig = portraitBig;
		this.portraitMiddle = portraitMiddle;
		this.portraitSmall = portraitSmall;
		this.placeOrigin1 = placeOrigin1;
		this.placeOrigin2 = placeOrigin2;
		this.profession = profession;
		this.post = post;
		this.autograph = autograph;
		this.affective = affective;
	}

	@Id
	@Column (
	    name = "user_id",
	    unique = true,
	    nullable = false)
	public int getUserId() {

		return this.userId;
	}

	public void setUserId(int userId) {

		this.userId = userId;
	}

	@Column (
	    name = "real_name",
	    length = 60)
	public String getRealName() {

		return this.realName;
	}

	public void setRealName(String realName) {

		this.realName = realName;
	}

	@Column (
	    name = "gender")
	public Byte getGender() {

		return this.gender;
	}

	public void setGender(Byte gender) {

		this.gender = gender;
	}

	@Column (
	    name = "birthday",
	    length = 10)
	public String getBirthday() {

		return this.birthday;
	}

	public void setBirthday(String birthday) {

		this.birthday = birthday;
	}

	@Column (
	    name = "age")
	public Integer getAge() {

		return this.age;
	}

	public void setAge(Integer age) {

		this.age = age;
	}

	@Column (
	    name = "phone_tel",
	    length = 60)
	public String getPhoneTel() {

		return this.phoneTel;
	}

	public void setPhoneTel(String phoneTel) {

		this.phoneTel = phoneTel;
	}

	@Column (
	    name = "update_time")
	public Integer getUpdateTime() {

		return this.updateTime;
	}

	public void setUpdateTime(Integer updateTime) {

		this.updateTime = updateTime;
	}

	@Column (
	    name = "portrait_big")
	public String getPortraitBig() {

		return this.portraitBig;
	}

	public void setPortraitBig(String portraitBig) {

		this.portraitBig = portraitBig;
	}

	@Column (
	    name = "portrait_middle")
	public String getPortraitMiddle() {

		return this.portraitMiddle;
	}

	public void setPortraitMiddle(String portraitMiddle) {

		this.portraitMiddle = portraitMiddle;
	}

	@Column (
	    name = "portrait_small")
	public String getPortraitSmall() {

		return this.portraitSmall;
	}

	public void setPortraitSmall(String portraitSmall) {

		this.portraitSmall = portraitSmall;
	}

	@Column (
	    name = "place_origin1")
	public Integer getPlaceOrigin1() {

		return this.placeOrigin1;
	}

	public void setPlaceOrigin1(Integer placeOrigin1) {

		this.placeOrigin1 = placeOrigin1;
	}

	@Column (
	    name = "place_origin2")
	public Integer getPlaceOrigin2() {

		return this.placeOrigin2;
	}

	public void setPlaceOrigin2(Integer placeOrigin2) {

		this.placeOrigin2 = placeOrigin2;
	}

	@Column (
	    name = "profession",
	    length = 100)
	public String getProfession() {

		return this.profession;
	}

	public void setProfession(String profession) {

		this.profession = profession;
	}

	@Column (
	    name = "post")
	public Integer getPost() {

		return this.post;
	}

	public void setPost(Integer post) {

		this.post = post;
	}

	@Column (
	    name = "autograph",
	    length = 100)
	public String getAutograph() {

		return this.autograph;
	}

	public void setAutograph(String autograph) {

		this.autograph = autograph;
	}

	@Column (
	    name = "affective")
	public Integer getAffective() {

		return this.affective;
	}

	public void setAffective(Integer affective) {

		this.affective = affective;
	}

}
