package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TddMember generated by hbm2java
 */
@Entity
@Table (
    name = "tdd_member",
    catalog = "rms")
public class TddMember implements java.io.Serializable {

	private Integer	userId;

	private String	userName;

	private String	email;

	private String	password;

	private Long	phoneMob;

	private int	    type;

	private byte	state;

	private Byte	emailV;

	private Byte	mobileV;

	private Integer	regTime;

	private Integer	lastLogin;

	private String	lastIp;

	private int	    logins;

	private byte	agree;

	private Integer	registerType;

	private Integer	schoolId;

	public TddMember() {

	}

	public TddMember(String userName, String password, int type, byte state, int logins, byte agree) {

		this.userName = userName;
		this.password = password;
		this.type = type;
		this.state = state;
		this.logins = logins;
		this.agree = agree;
	}

	public TddMember(String userName, String email, String password, Long phoneMob, int type, byte state, Byte emailV, Byte mobileV,
	        Integer regTime, Integer lastLogin, String lastIp, int logins, byte agree, Integer registerType, Integer schoolId) {

		this.userName = userName;
		this.email = email;
		this.password = password;
		this.phoneMob = phoneMob;
		this.type = type;
		this.state = state;
		this.emailV = emailV;
		this.mobileV = mobileV;
		this.regTime = regTime;
		this.lastLogin = lastLogin;
		this.lastIp = lastIp;
		this.logins = logins;
		this.agree = agree;
		this.registerType = registerType;
		this.schoolId = schoolId;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "user_id",
	    unique = true,
	    nullable = false)
	public Integer getUserId() {

		return this.userId;
	}

	public void setUserId(Integer userId) {

		this.userId = userId;
	}

	@Column (
	    name = "user_name",
	    nullable = false,
	    length = 60)
	public String getUserName() {

		return this.userName;
	}

	public void setUserName(String userName) {

		this.userName = userName;
	}

	@Column (
	    name = "email",
	    length = 60)
	public String getEmail() {

		return this.email;
	}

	public void setEmail(String email) {

		this.email = email;
	}

	@Column (
	    name = "password",
	    nullable = false,
	    length = 32)
	public String getPassword() {

		return this.password;
	}

	public void setPassword(String password) {

		this.password = password;
	}

	@Column (
	    name = "phone_mob")
	public Long getPhoneMob() {

		return this.phoneMob;
	}

	public void setPhoneMob(Long phoneMob) {

		this.phoneMob = phoneMob;
	}

	@Column (
	    name = "type",
	    nullable = false)
	public int getType() {

		return this.type;
	}

	public void setType(int type) {

		this.type = type;
	}

	@Column (
	    name = "state",
	    nullable = false)
	public byte getState() {

		return this.state;
	}

	public void setState(byte state) {

		this.state = state;
	}

	@Column (
	    name = "email_v")
	public Byte getEmailV() {

		return this.emailV;
	}

	public void setEmailV(Byte emailV) {

		this.emailV = emailV;
	}

	@Column (
	    name = "mobile_v")
	public Byte getMobileV() {

		return this.mobileV;
	}

	public void setMobileV(Byte mobileV) {

		this.mobileV = mobileV;
	}

	@Column (
	    name = "reg_time")
	public Integer getRegTime() {

		return this.regTime;
	}

	public void setRegTime(Integer regTime) {

		this.regTime = regTime;
	}

	@Column (
	    name = "last_login")
	public Integer getLastLogin() {

		return this.lastLogin;
	}

	public void setLastLogin(Integer lastLogin) {

		this.lastLogin = lastLogin;
	}

	@Column (
	    name = "last_ip",
	    length = 15)
	public String getLastIp() {

		return this.lastIp;
	}

	public void setLastIp(String lastIp) {

		this.lastIp = lastIp;
	}

	@Column (
	    name = "logins",
	    nullable = false)
	public int getLogins() {

		return this.logins;
	}

	public void setLogins(int logins) {

		this.logins = logins;
	}

	@Column (
	    name = "agree",
	    nullable = false)
	public byte getAgree() {

		return this.agree;
	}

	public void setAgree(byte agree) {

		this.agree = agree;
	}

	@Column (
	    name = "register_type")
	public Integer getRegisterType() {

		return this.registerType;
	}

	public void setRegisterType(Integer registerType) {

		this.registerType = registerType;
	}

	@Column (
	    name = "school_id")
	public Integer getSchoolId() {

		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {

		this.schoolId = schoolId;
	}

}
