package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TvAdConfig generated by hbm2java
 */
@Entity
@Table (
    name = "tv_ad_config",
    catalog = "rms")
public class TvAdConfig implements java.io.Serializable {

	private Integer	tacId;

	private int	    tacTaId;

	private int	    tacStation;

	public TvAdConfig() {

	}

	public TvAdConfig(int tacTaId, int tacStation) {

		this.tacTaId = tacTaId;
		this.tacStation = tacStation;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tac_id",
	    unique = true,
	    nullable = false)
	public Integer getTacId() {

		return this.tacId;
	}

	public void setTacId(Integer tacId) {

		this.tacId = tacId;
	}

	@Column (
	    name = "tac_ta_id",
	    nullable = false)
	public int getTacTaId() {

		return this.tacTaId;
	}

	public void setTacTaId(int tacTaId) {

		this.tacTaId = tacTaId;
	}

	@Column (
	    name = "tac_station",
	    nullable = false)
	public int getTacStation() {

		return this.tacStation;
	}

	public void setTacStation(int tacStation) {

		this.tacStation = tacStation;
	}

}
