package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvAd generated by hbm2java
 */
@Entity
@Table (
    name = "tv_ad",
    catalog = "rms")
public class TvAd implements java.io.Serializable {

	private Integer	taId;

	private String	taName;

	private String	taSourceUrl;

	private int	    taSort;

	private Date	taAddtime;

	private Integer	taAdduserId;

	private Integer	taModfiyuserId;

	private Date	taModfiytime;

	private Date	taStarttime;

	private Date	taEndtime;

	private Integer	taGroupId;

	private byte	taStation;

	private Integer	taPlayCount;

	private Integer	taTime;

	private String	taAdUrl;

	private Float	taMoney;

	private int	    taState;

	public TvAd() {

	}

	public TvAd(String taName, String taSourceUrl, int taSort, byte taStation, String taAdUrl, int taState) {

		this.taName = taName;
		this.taSourceUrl = taSourceUrl;
		this.taSort = taSort;
		this.taStation = taStation;
		this.taAdUrl = taAdUrl;
		this.taState = taState;
	}

	public TvAd(String taName, String taSourceUrl, int taSort, Date taAddtime, Integer taAdduserId, Integer taModfiyuserId,
	        Date taModfiytime, Date taStarttime, Date taEndtime, Integer taGroupId, byte taStation, Integer taPlayCount, Integer taTime,
	        String taAdUrl, Float taMoney, int taState) {

		this.taName = taName;
		this.taSourceUrl = taSourceUrl;
		this.taSort = taSort;
		this.taAddtime = taAddtime;
		this.taAdduserId = taAdduserId;
		this.taModfiyuserId = taModfiyuserId;
		this.taModfiytime = taModfiytime;
		this.taStarttime = taStarttime;
		this.taEndtime = taEndtime;
		this.taGroupId = taGroupId;
		this.taStation = taStation;
		this.taPlayCount = taPlayCount;
		this.taTime = taTime;
		this.taAdUrl = taAdUrl;
		this.taMoney = taMoney;
		this.taState = taState;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "ta_id",
	    unique = true,
	    nullable = false)
	public Integer getTaId() {

		return this.taId;
	}

	public void setTaId(Integer taId) {

		this.taId = taId;
	}

	@Column (
	    name = "ta_name",
	    nullable = false,
	    length = 200)
	public String getTaName() {

		return this.taName;
	}

	public void setTaName(String taName) {

		this.taName = taName;
	}

	@Column (
	    name = "ta_source_url",
	    nullable = false)
	public String getTaSourceUrl() {

		return this.taSourceUrl;
	}

	public void setTaSourceUrl(String taSourceUrl) {

		this.taSourceUrl = taSourceUrl;
	}

	@Column (
	    name = "ta_sort",
	    nullable = false)
	public int getTaSort() {

		return this.taSort;
	}

	public void setTaSort(int taSort) {

		this.taSort = taSort;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "ta_addtime",
	    length = 19)
	public Date getTaAddtime() {

		return this.taAddtime;
	}

	public void setTaAddtime(Date taAddtime) {

		this.taAddtime = taAddtime;
	}

	@Column (
	    name = "ta_adduser_id")
	public Integer getTaAdduserId() {

		return this.taAdduserId;
	}

	public void setTaAdduserId(Integer taAdduserId) {

		this.taAdduserId = taAdduserId;
	}

	@Column (
	    name = "ta_modfiyuser_id")
	public Integer getTaModfiyuserId() {

		return this.taModfiyuserId;
	}

	public void setTaModfiyuserId(Integer taModfiyuserId) {

		this.taModfiyuserId = taModfiyuserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "ta_modfiytime",
	    length = 19)
	public Date getTaModfiytime() {

		return this.taModfiytime;
	}

	public void setTaModfiytime(Date taModfiytime) {

		this.taModfiytime = taModfiytime;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "ta_starttime",
	    length = 19)
	public Date getTaStarttime() {

		return this.taStarttime;
	}

	public void setTaStarttime(Date taStarttime) {

		this.taStarttime = taStarttime;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "ta_endtime",
	    length = 19)
	public Date getTaEndtime() {

		return this.taEndtime;
	}

	public void setTaEndtime(Date taEndtime) {

		this.taEndtime = taEndtime;
	}

	@Column (
	    name = "ta_group_id")
	public Integer getTaGroupId() {

		return this.taGroupId;
	}

	public void setTaGroupId(Integer taGroupId) {

		this.taGroupId = taGroupId;
	}

	@Column (
	    name = "ta_station",
	    nullable = false)
	public byte getTaStation() {

		return this.taStation;
	}

	public void setTaStation(byte taStation) {

		this.taStation = taStation;
	}

	@Column (
	    name = "ta_play_count")
	public Integer getTaPlayCount() {

		return this.taPlayCount;
	}

	public void setTaPlayCount(Integer taPlayCount) {

		this.taPlayCount = taPlayCount;
	}

	@Column (
	    name = "ta_time")
	public Integer getTaTime() {

		return this.taTime;
	}

	public void setTaTime(Integer taTime) {

		this.taTime = taTime;
	}

	@Column (
	    name = "ta_ad_url",
	    nullable = false)
	public String getTaAdUrl() {

		return this.taAdUrl;
	}

	public void setTaAdUrl(String taAdUrl) {

		this.taAdUrl = taAdUrl;
	}

	@Column (
	    name = "ta_money",
	    precision = 11)
	public Float getTaMoney() {

		return this.taMoney;
	}

	public void setTaMoney(Float taMoney) {

		this.taMoney = taMoney;
	}

	@Column (
	    name = "ta_state",
	    nullable = false)
	public int getTaState() {

		return this.taState;
	}

	public void setTaState(int taState) {

		this.taState = taState;
	}

}
