package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvBrowseRecordMore generated by hbm2java
 */
@Entity
@Table (
    name = "tv_browse_record_more",
    catalog = "rms")
public class TvBrowseRecordMore implements java.io.Serializable {

	private Integer	id;

	private Integer	tvId;

	private Date	addtime;

	private Integer	userId;

	private Double	progress;

	public TvBrowseRecordMore() {

	}

	public TvBrowseRecordMore(Integer tvId, Date addtime, Integer userId, Double progress) {

		this.tvId = tvId;
		this.addtime = addtime;
		this.userId = userId;
		this.progress = progress;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "id",
	    unique = true,
	    nullable = false)
	public Integer getId() {

		return this.id;
	}

	public void setId(Integer id) {

		this.id = id;
	}

	@Column (
	    name = "tv_id")
	public Integer getTvId() {

		return this.tvId;
	}

	public void setTvId(Integer tvId) {

		this.tvId = tvId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "addtime",
	    length = 19)
	public Date getAddtime() {

		return this.addtime;
	}

	public void setAddtime(Date addtime) {

		this.addtime = addtime;
	}

	@Column (
	    name = "user_id")
	public Integer getUserId() {

		return this.userId;
	}

	public void setUserId(Integer userId) {

		this.userId = userId;
	}

	@Column (
	    name = "progress",
	    precision = 10,
	    scale = 3)
	public Double getProgress() {

		return this.progress;
	}

	public void setProgress(Double progress) {

		this.progress = progress;
	}

}
