package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvBrowseRecord generated by hbm2java
 */
@Entity
@Table (
    name = "tv_browse_record",
    catalog = "rms")
public class TvBrowseRecord implements java.io.Serializable {

	private Integer	tbrId;

	private Integer	tbrUserId;

	private Double	tbrTvProgress;

	private Date	tbrAddtime;

	private Integer	tbrTvId;

	private Integer	tbrPlayCount;

	public TvBrowseRecord() {

	}

	public TvBrowseRecord(Integer tbrUserId, Double tbrTvProgress, Date tbrAddtime, Integer tbrTvId, Integer tbrPlayCount) {

		this.tbrUserId = tbrUserId;
		this.tbrTvProgress = tbrTvProgress;
		this.tbrAddtime = tbrAddtime;
		this.tbrTvId = tbrTvId;
		this.tbrPlayCount = tbrPlayCount;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tbr_id",
	    unique = true,
	    nullable = false)
	public Integer getTbrId() {

		return this.tbrId;
	}

	public void setTbrId(Integer tbrId) {

		this.tbrId = tbrId;
	}

	@Column (
	    name = "tbr_user_id")
	public Integer getTbrUserId() {

		return this.tbrUserId;
	}

	public void setTbrUserId(Integer tbrUserId) {

		this.tbrUserId = tbrUserId;
	}

	@Column (
	    name = "tbr_tv_progress",
	    precision = 11,
	    scale = 3)
	public Double getTbrTvProgress() {

		return this.tbrTvProgress;
	}

	public void setTbrTvProgress(Double tbrTvProgress) {

		this.tbrTvProgress = tbrTvProgress;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tbr_addtime",
	    length = 19)
	public Date getTbrAddtime() {

		return this.tbrAddtime;
	}

	public void setTbrAddtime(Date tbrAddtime) {

		this.tbrAddtime = tbrAddtime;
	}

	@Column (
	    name = "tbr_tv_id")
	public Integer getTbrTvId() {

		return this.tbrTvId;
	}

	public void setTbrTvId(Integer tbrTvId) {

		this.tbrTvId = tbrTvId;
	}

	@Column (
	    name = "tbr_play_count")
	public Integer getTbrPlayCount() {

		return this.tbrPlayCount;
	}

	public void setTbrPlayCount(Integer tbrPlayCount) {

		this.tbrPlayCount = tbrPlayCount;
	}

}
