package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvChannel generated by hbm2java
 */
@Entity
@Table (
    name = "tv_channel",
    catalog = "rms")
public class TvChannel implements java.io.Serializable {

	private Integer	tcId;

	private String	tcName;

	private String	tcDesc;

	private Date	tcAddtime;

	private Integer	tcAdduserId;

	private Integer	tcModfiyuserId;

	private Date	tcModfiytime;

	private byte	tcState;

	private Integer	tcParentid;

	private int	    tcLevel;

	private int	    tcSort;

	private Byte	tcHeadShow;

	private String	tcImage;

	public TvChannel() {

	}

	public TvChannel(String tcName, byte tcState, int tcLevel, int tcSort) {

		this.tcName = tcName;
		this.tcState = tcState;
		this.tcLevel = tcLevel;
		this.tcSort = tcSort;
	}

	public TvChannel(String tcName, String tcDesc, Date tcAddtime, Integer tcAdduserId, Integer tcModfiyuserId, Date tcModfiytime,
	        byte tcState, Integer tcParentid, int tcLevel, int tcSort, Byte tcHeadShow, String tcImage) {

		this.tcName = tcName;
		this.tcDesc = tcDesc;
		this.tcAddtime = tcAddtime;
		this.tcAdduserId = tcAdduserId;
		this.tcModfiyuserId = tcModfiyuserId;
		this.tcModfiytime = tcModfiytime;
		this.tcState = tcState;
		this.tcParentid = tcParentid;
		this.tcLevel = tcLevel;
		this.tcSort = tcSort;
		this.tcHeadShow = tcHeadShow;
		this.tcImage = tcImage;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tc_id",
	    unique = true,
	    nullable = false)
	public Integer getTcId() {

		return this.tcId;
	}

	public void setTcId(Integer tcId) {

		this.tcId = tcId;
	}

	@Column (
	    name = "tc_name",
	    nullable = false)
	public String getTcName() {

		return this.tcName;
	}

	public void setTcName(String tcName) {

		this.tcName = tcName;
	}

	@Column (
	    name = "tc_desc",
	    length = 65535)
	public String getTcDesc() {

		return this.tcDesc;
	}

	public void setTcDesc(String tcDesc) {

		this.tcDesc = tcDesc;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tc_addtime",
	    length = 19)
	public Date getTcAddtime() {

		return this.tcAddtime;
	}

	public void setTcAddtime(Date tcAddtime) {

		this.tcAddtime = tcAddtime;
	}

	@Column (
	    name = "tc_adduser_id")
	public Integer getTcAdduserId() {

		return this.tcAdduserId;
	}

	public void setTcAdduserId(Integer tcAdduserId) {

		this.tcAdduserId = tcAdduserId;
	}

	@Column (
	    name = "tc_modfiyuser_id")
	public Integer getTcModfiyuserId() {

		return this.tcModfiyuserId;
	}

	public void setTcModfiyuserId(Integer tcModfiyuserId) {

		this.tcModfiyuserId = tcModfiyuserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tc_modfiytime",
	    length = 19)
	public Date getTcModfiytime() {

		return this.tcModfiytime;
	}

	public void setTcModfiytime(Date tcModfiytime) {

		this.tcModfiytime = tcModfiytime;
	}

	@Column (
	    name = "tc_state",
	    nullable = false)
	public byte getTcState() {

		return this.tcState;
	}

	public void setTcState(byte tcState) {

		this.tcState = tcState;
	}

	@Column (
	    name = "tc_parentid")
	public Integer getTcParentid() {

		return this.tcParentid;
	}

	public void setTcParentid(Integer tcParentid) {

		this.tcParentid = tcParentid;
	}

	@Column (
	    name = "tc_level",
	    nullable = false)
	public int getTcLevel() {

		return this.tcLevel;
	}

	public void setTcLevel(int tcLevel) {

		this.tcLevel = tcLevel;
	}

	@Column (
	    name = "tc_sort",
	    nullable = false)
	public int getTcSort() {

		return this.tcSort;
	}

	public void setTcSort(int tcSort) {

		this.tcSort = tcSort;
	}

	@Column (
	    name = "tc_head_show")
	public Byte getTcHeadShow() {

		return this.tcHeadShow;
	}

	public void setTcHeadShow(Byte tcHeadShow) {

		this.tcHeadShow = tcHeadShow;
	}

	@Column (
	    name = "tc_image",
	    length = 50)
	public String getTcImage() {

		return this.tcImage;
	}

	public void setTcImage(String tcImage) {

		this.tcImage = tcImage;
	}

}
