package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvCollectionRecord generated by hbm2java
 */
@Entity
@Table (
    name = "tv_collection_record",
    catalog = "rms")
public class TvCollectionRecord implements java.io.Serializable {

	private Integer	tcrId;

	private int	    tcrUserId;

	private Date	tcrAddtime;

	private int	    tcrTvId;

	public TvCollectionRecord() {

	}

	public TvCollectionRecord(int tcrUserId, Date tcrAddtime, int tcrTvId) {

		this.tcrUserId = tcrUserId;
		this.tcrAddtime = tcrAddtime;
		this.tcrTvId = tcrTvId;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tcr_id",
	    unique = true,
	    nullable = false)
	public Integer getTcrId() {

		return this.tcrId;
	}

	public void setTcrId(Integer tcrId) {

		this.tcrId = tcrId;
	}

	@Column (
	    name = "tcr_user_id",
	    nullable = false)
	public int getTcrUserId() {

		return this.tcrUserId;
	}

	public void setTcrUserId(int tcrUserId) {

		this.tcrUserId = tcrUserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tcr_addtime",
	    nullable = false,
	    length = 19)
	public Date getTcrAddtime() {

		return this.tcrAddtime;
	}

	public void setTcrAddtime(Date tcrAddtime) {

		this.tcrAddtime = tcrAddtime;
	}

	@Column (
	    name = "tcr_tv_id",
	    nullable = false)
	public int getTcrTvId() {

		return this.tcrTvId;
	}

	public void setTcrTvId(int tcrTvId) {

		this.tcrTvId = tcrTvId;
	}

}
