package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvRecommended generated by hbm2java
 */
@Entity
@Table (
    name = "tv_recommended",
    catalog = "rms")
public class TvRecommended implements java.io.Serializable {

	private Integer	trId;

	private TvInfo	tvInfo;

	private int	    trSort;

	private Date	trAddtime;

	private Integer	trAdduserId;

	private byte	trType;

	private Integer	trChannelId;

	private Integer	trModfiyuserId;

	private Date	trModfiytime;

	private String	trImages;

	private String	trImagesSquare;

	private String	trName;

	public TvRecommended() {

	}

	public TvRecommended(TvInfo tvInfo, int trSort, byte trType) {

		this.tvInfo = tvInfo;
		this.trSort = trSort;
		this.trType = trType;
	}

	public TvRecommended(TvInfo tvInfo, int trSort, Date trAddtime, Integer trAdduserId, byte trType, Integer trChannelId,
	        Integer trModfiyuserId, Date trModfiytime, String trImages, String trImagesSquare, String trName) {

		this.tvInfo = tvInfo;
		this.trSort = trSort;
		this.trAddtime = trAddtime;
		this.trAdduserId = trAdduserId;
		this.trType = trType;
		this.trChannelId = trChannelId;
		this.trModfiyuserId = trModfiyuserId;
		this.trModfiytime = trModfiytime;
		this.trImages = trImages;
		this.trImagesSquare = trImagesSquare;
		this.trName = trName;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tr_id",
	    unique = true,
	    nullable = false)
	public Integer getTrId() {

		return this.trId;
	}

	public void setTrId(Integer trId) {

		this.trId = trId;
	}

	@ManyToOne (
	    fetch = FetchType.LAZY)
	@JoinColumn (
	    name = "tr_tv_id",
	    nullable = false)
	public TvInfo getTvInfo() {

		return this.tvInfo;
	}

	public void setTvInfo(TvInfo tvInfo) {

		this.tvInfo = tvInfo;
	}

	@Column (
	    name = "tr_sort",
	    nullable = false)
	public int getTrSort() {

		return this.trSort;
	}

	public void setTrSort(int trSort) {

		this.trSort = trSort;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tr_addtime",
	    length = 19)
	public Date getTrAddtime() {

		return this.trAddtime;
	}

	public void setTrAddtime(Date trAddtime) {

		this.trAddtime = trAddtime;
	}

	@Column (
	    name = "tr_adduser_id")
	public Integer getTrAdduserId() {

		return this.trAdduserId;
	}

	public void setTrAdduserId(Integer trAdduserId) {

		this.trAdduserId = trAdduserId;
	}

	@Column (
	    name = "tr_type",
	    nullable = false)
	public byte getTrType() {

		return this.trType;
	}

	public void setTrType(byte trType) {

		this.trType = trType;
	}

	@Column (
	    name = "tr_channel_id")
	public Integer getTrChannelId() {

		return this.trChannelId;
	}

	public void setTrChannelId(Integer trChannelId) {

		this.trChannelId = trChannelId;
	}

	@Column (
	    name = "tr_modfiyuser_id")
	public Integer getTrModfiyuserId() {

		return this.trModfiyuserId;
	}

	public void setTrModfiyuserId(Integer trModfiyuserId) {

		this.trModfiyuserId = trModfiyuserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tr_modfiytime",
	    length = 19)
	public Date getTrModfiytime() {

		return this.trModfiytime;
	}

	public void setTrModfiytime(Date trModfiytime) {

		this.trModfiytime = trModfiytime;
	}

	@Column (
	    name = "tr_images",
	    length = 100)
	public String getTrImages() {

		return this.trImages;
	}

	public void setTrImages(String trImages) {

		this.trImages = trImages;
	}

	@Column (
	    name = "tr_images_square",
	    length = 100)
	public String getTrImagesSquare() {

		return this.trImagesSquare;
	}

	public void setTrImagesSquare(String trImagesSquare) {

		this.trImagesSquare = trImagesSquare;
	}

	@Column (
	    name = "tr_name")
	public String getTrName() {

		return this.trName;
	}

	public void setTrName(String trName) {

		this.trName = trName;
	}

}
