package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvSearchRecord generated by hbm2java
 */
@Entity
@Table (
    name = "tv_search_record",
    catalog = "rms")
public class TvSearchRecord implements java.io.Serializable {

	private Integer	tsrId;

	private Integer	tsrUserId;

	private String	tsrContent;

	private Date	tsrAddtime;

	public TvSearchRecord() {

	}

	public TvSearchRecord(Integer tsrUserId, String tsrContent, Date tsrAddtime) {

		this.tsrUserId = tsrUserId;
		this.tsrContent = tsrContent;
		this.tsrAddtime = tsrAddtime;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tsr_id",
	    unique = true,
	    nullable = false)
	public Integer getTsrId() {

		return this.tsrId;
	}

	public void setTsrId(Integer tsrId) {

		this.tsrId = tsrId;
	}

	@Column (
	    name = "tsr_user_id")
	public Integer getTsrUserId() {

		return this.tsrUserId;
	}

	public void setTsrUserId(Integer tsrUserId) {

		this.tsrUserId = tsrUserId;
	}

	@Column (
	    name = "tsr_content")
	public String getTsrContent() {

		return this.tsrContent;
	}

	public void setTsrContent(String tsrContent) {

		this.tsrContent = tsrContent;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tsr_addtime",
	    length = 19)
	public Date getTsrAddtime() {

		return this.tsrAddtime;
	}

	public void setTsrAddtime(Date tsrAddtime) {

		this.tsrAddtime = tsrAddtime;
	}

}
