package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvUserGroup generated by hbm2java
 */
@Entity
@Table (
    name = "tv_user_group",
    catalog = "rms")
public class TvUserGroup implements java.io.Serializable {

	private Integer	tugId;

	private String	tugName;

	private String	tugDesc;

	private Integer	tugPlayCount;

	private Integer	tugCommentCount;

	private Date	tugAddtime;

	private Integer	tugAdduserId;

	private Integer	tugModfiyuserId;

	private Date	tugModfiytime;

	private Integer	tugState;

	public TvUserGroup() {

	}

	public TvUserGroup(String tugName, String tugDesc, Integer tugPlayCount, Integer tugCommentCount, Date tugAddtime,
	        Integer tugAdduserId, Integer tugModfiyuserId, Date tugModfiytime, Integer tugState) {

		this.tugName = tugName;
		this.tugDesc = tugDesc;
		this.tugPlayCount = tugPlayCount;
		this.tugCommentCount = tugCommentCount;
		this.tugAddtime = tugAddtime;
		this.tugAdduserId = tugAdduserId;
		this.tugModfiyuserId = tugModfiyuserId;
		this.tugModfiytime = tugModfiytime;
		this.tugState = tugState;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tug_id",
	    unique = true,
	    nullable = false)
	public Integer getTugId() {

		return this.tugId;
	}

	public void setTugId(Integer tugId) {

		this.tugId = tugId;
	}

	@Column (
	    name = "tug_name",
	    length = 50)
	public String getTugName() {

		return this.tugName;
	}

	public void setTugName(String tugName) {

		this.tugName = tugName;
	}

	@Column (
	    name = "tug_desc",
	    length = 65535)
	public String getTugDesc() {

		return this.tugDesc;
	}

	public void setTugDesc(String tugDesc) {

		this.tugDesc = tugDesc;
	}

	@Column (
	    name = "tug_play_count")
	public Integer getTugPlayCount() {

		return this.tugPlayCount;
	}

	public void setTugPlayCount(Integer tugPlayCount) {

		this.tugPlayCount = tugPlayCount;
	}

	@Column (
	    name = "tug_comment_count")
	public Integer getTugCommentCount() {

		return this.tugCommentCount;
	}

	public void setTugCommentCount(Integer tugCommentCount) {

		this.tugCommentCount = tugCommentCount;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tug_addtime",
	    length = 19)
	public Date getTugAddtime() {

		return this.tugAddtime;
	}

	public void setTugAddtime(Date tugAddtime) {

		this.tugAddtime = tugAddtime;
	}

	@Column (
	    name = "tug_adduser_id")
	public Integer getTugAdduserId() {

		return this.tugAdduserId;
	}

	public void setTugAdduserId(Integer tugAdduserId) {

		this.tugAdduserId = tugAdduserId;
	}

	@Column (
	    name = "tug_modfiyuser_id")
	public Integer getTugModfiyuserId() {

		return this.tugModfiyuserId;
	}

	public void setTugModfiyuserId(Integer tugModfiyuserId) {

		this.tugModfiyuserId = tugModfiyuserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tug_modfiytime",
	    length = 19)
	public Date getTugModfiytime() {

		return this.tugModfiytime;
	}

	public void setTugModfiytime(Date tugModfiytime) {

		this.tugModfiytime = tugModfiytime;
	}

	@Column (
	    name = "tug_state")
	public Integer getTugState() {

		return this.tugState;
	}

	public void setTugState(Integer tugState) {

		this.tugState = tugState;
	}

}
