package com.rms.entity.tdd;

// Generated 2015-8-26 14:10:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TvVoteRecord generated by hbm2java
 */
@Entity
@Table (
    name = "tv_vote_record",
    catalog = "rms")
public class TvVoteRecord implements java.io.Serializable {

	private Integer	tvrId;

	private Integer	tvrUserId;

	private Date	tvrAddtime;

	private int	    tvrTvId;

	private String	ip;

	public TvVoteRecord() {

	}

	public TvVoteRecord(Date tvrAddtime, int tvrTvId) {

		this.tvrAddtime = tvrAddtime;
		this.tvrTvId = tvrTvId;
	}

	public TvVoteRecord(Integer tvrUserId, Date tvrAddtime, int tvrTvId, String ip) {

		this.tvrUserId = tvrUserId;
		this.tvrAddtime = tvrAddtime;
		this.tvrTvId = tvrTvId;
		this.ip = ip;
	}

	@Id
	@GeneratedValue (
	    strategy = IDENTITY)
	@Column (
	    name = "tvr_id",
	    unique = true,
	    nullable = false)
	public Integer getTvrId() {

		return this.tvrId;
	}

	public void setTvrId(Integer tvrId) {

		this.tvrId = tvrId;
	}

	@Column (
	    name = "tvr_user_id")
	public Integer getTvrUserId() {

		return this.tvrUserId;
	}

	public void setTvrUserId(Integer tvrUserId) {

		this.tvrUserId = tvrUserId;
	}

	@Temporal (TemporalType.TIMESTAMP)
	@Column (
	    name = "tvr_addtime",
	    nullable = false,
	    length = 19)
	public Date getTvrAddtime() {

		return this.tvrAddtime;
	}

	public void setTvrAddtime(Date tvrAddtime) {

		this.tvrAddtime = tvrAddtime;
	}

	@Column (
	    name = "tvr_tv_id",
	    nullable = false)
	public int getTvrTvId() {

		return this.tvrTvId;
	}

	public void setTvrTvId(int tvrTvId) {

		this.tvrTvId = tvrTvId;
	}

	@Column (
	    name = "ip")
	public String getIp() {

		return this.ip;
	}

	public void setIp(String ip) {

		this.ip = ip;
	}

}
